/*
 * Web Files Implementation for ESP32-S3 LED Controller
 * 现代化Web控制界面
 */

#include "web_files.h"
#include <string.h>

// 完整的HTML页面内容
const char index_html_content[] = 
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"    <meta charset='UTF-8'>"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"    <title>ESP32-S3 LED控制器</title>"
"    <style>"
"        * { margin: 0; padding: 0; box-sizing: border-box; }"
"        body {"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
"            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
"            min-height: 100vh; color: #333; padding: 20px;"
"        }"
"        .container {"
"            max-width: 1000px; margin: 0 auto;"
"            background: rgba(255, 255, 255, 0.95);"
"            border-radius: 20px; overflow: hidden;"
"            box-shadow: 0 20px 40px rgba(0,0,0,0.1);"
"        }"
"        .header {"
"            background: linear-gradient(45deg, #667eea, #764ba2);"
"            color: white; padding: 30px; text-align: center;"
"        }"
"        .header h1 { font-size: 2.5em; margin-bottom: 10px; }"
"        .status { font-size: 1.1em; opacity: 0.9; }"
"        .main { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; padding: 30px; }"
"        .card {"
"            background: #f8f9fa; border-radius: 15px; padding: 25px;"
"            box-shadow: 0 5px 15px rgba(0,0,0,0.08);"
"            border: 1px solid #e9ecef;"
"        }"
"        .card h3 { color: #495057; margin-bottom: 20px; font-size: 1.3em; }"
"        .color-controls { display: flex; flex-direction: column; gap: 20px; }"
"        .slider-group { display: flex; flex-direction: column; gap: 8px; }"
"        .slider-group label {"
"            display: flex; justify-content: space-between; align-items: center;"
"            font-weight: 600; color: #495057;"
"        }"
"        .slider {"
"            width: 100%; height: 10px; border-radius: 5px;"
"            background: #e9ecef; outline: none; cursor: pointer;"
"            -webkit-appearance: none; appearance: none;"
"        }"
"        .slider::-webkit-slider-thumb {"
"            -webkit-appearance: none; appearance: none;"
"            width: 24px; height: 24px; border-radius: 50%;"
"            background: #667eea; cursor: pointer;"
"            box-shadow: 0 2px 6px rgba(0,0,0,0.2);"
"        }"
"        .red-slider::-webkit-slider-thumb { background: #dc3545; }"
"        .green-slider::-webkit-slider-thumb { background: #28a745; }"
"        .blue-slider::-webkit-slider-thumb { background: #007bff; }"
"        .brightness-slider::-webkit-slider-thumb { background: #ffc107; }"
"        .preview-area { text-align: center; }"
"        .color-preview {"
"            width: 200px; height: 200px; border-radius: 50%;"
"            margin: 20px auto; box-shadow: 0 10px 30px rgba(0,0,0,0.2);"
"            background: linear-gradient(45deg, #667eea, #764ba2);"
"            transition: all 0.3s ease;"
"        }"
"        .color-info {"
"            display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px;"
"            margin-top: 20px;"
"        }"
"        .info-item {"
"            background: white; padding: 15px; border-radius: 10px;"
"            border: 2px solid #e9ecef; text-align: center;"
"        }"
"        .info-label { font-size: 0.9em; color: #6c757d; }"
"        .info-value { font-size: 1.2em; font-weight: bold; color: #495057; }"
"        .button-grid {"
"            display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px;"
"            margin-top: 20px;"
"        }"
"        .btn {"
"            padding: 15px 20px; border: none; border-radius: 10px;"
"            font-size: 1em; font-weight: 600; cursor: pointer;"
"            transition: all 0.3s ease; text-align: center;"
"        }"
"        .btn:hover { transform: translateY(-2px); box-shadow: 0 5px 15px rgba(0,0,0,0.2); }"
"        .btn-power { background: #28a745; color: white; }"
"        .btn-power.off { background: #6c757d; }"
"        .btn-effect { background: #667eea; color: white; }"
"        .btn-effect.active { background: #495057; }"
"        .preset-colors {"
"            display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px;"
"            margin-top: 15px;"
"        }"
"        .preset-btn {"
"            width: 100%; height: 50px; border: none; border-radius: 8px;"
"            cursor: pointer; transition: all 0.3s ease;"
"            font-weight: bold; color: white; text-shadow: 0 1px 2px rgba(0,0,0,0.3);"
"        }"
"        .preset-btn:hover { transform: scale(1.05); }"
"        .wifi-info {"
"            background: #e7f3ff; border: 1px solid #b3d9ff;"
"            border-radius: 10px; padding: 15px; margin-top: 15px;"
"        }"
"        .notification {"
"            position: fixed; top: 20px; right: 20px; padding: 15px 20px;"
"            border-radius: 8px; color: white; font-weight: 600;"
"            transform: translateX(100%); transition: transform 0.3s ease;"
"            z-index: 1000; max-width: 300px;"
"        }"
"        .notification.show { transform: translateX(0); }"
"        .notification.success { background: #28a745; }"
"        .notification.error { background: #dc3545; }"
"        @media (max-width: 768px) {"
"            .main { grid-template-columns: 1fr; gap: 20px; }"
"            .color-info { grid-template-columns: repeat(2, 1fr); }"
"        }"
"    </style>"
"</head>"
"<body>"
"    <div class='container'>"
"        <div class='header'>"
"            <h1>🌈 ESP32-S3 LED控制器</h1>"
"            <div class='status' id='status'>🔗 NAT网络转发已启用 - 设备可访问互联网</div>"
"        </div>"
"        <div class='main'>"
"            <div class='control-panel'>"
"                <div class='card'>"
"                    <h3>🎨 颜色控制</h3>"
"                    <div class='color-controls'>"
"                        <div class='slider-group'>"
"                            <label>🔴 红色 <span id='r-val'>255</span></label>"
"                            <input type='range' id='r-slider' class='slider red-slider' min='0' max='255' value='255'>"
"                        </div>"
"                        <div class='slider-group'>"
"                            <label>🟢 绿色 <span id='g-val'>255</span></label>"
"                            <input type='range' id='g-slider' class='slider green-slider' min='0' max='255' value='255'>"
"                        </div>"
"                        <div class='slider-group'>"
"                            <label>🔵 蓝色 <span id='b-val'>255</span></label>"
"                            <input type='range' id='b-slider' class='slider blue-slider' min='0' max='255' value='255'>"
"                        </div>"
"                        <div class='slider-group'>"
"                            <label>💡 亮度 <span id='brightness-val'>50%</span></label>"
"                            <input type='range' id='brightness-slider' class='slider brightness-slider' min='0' max='100' value='50'>"
"                        </div>"
"                    </div>"
"                </div>"
"                <div class='card'>"
"                    <h3>⚡ 控制面板</h3>"
"                    <button class='btn btn-power' id='power-btn' onclick='togglePower()'>💡 开启LED</button>"
"                    <div class='button-grid'>"
"                        <button class='btn btn-effect active' onclick='setEffect(\"static\")'>🌟 静态</button>"
"                        <button class='btn btn-effect' onclick='setEffect(\"rainbow\")'>🌈 彩虹</button>"
"                        <button class='btn btn-effect' onclick='setEffect(\"breath\")'>💨 呼吸</button>"
"                        <button class='btn btn-effect' onclick='setEffect(\"blink\")'>⚡闪烁</button>"
"                    </div>"
"                </div>"
"                <div class='card'>"
"                    <h3>🎯 预设颜色</h3>"
"                    <div class='preset-colors'>"
"                        <button class='preset-btn' style='background:#dc3545' onclick='setColor(255,0,0)'>红</button>"
"                        <button class='preset-btn' style='background:#28a745' onclick='setColor(0,255,0)'>绿</button>"
"                        <button class='preset-btn' style='background:#007bff' onclick='setColor(0,0,255)'>蓝</button>"
"                        <button class='preset-btn' style='background:#ffc107;color:#000' onclick='setColor(255,255,0)'>黄</button>"
"                        <button class='preset-btn' style='background:#e83e8c' onclick='setColor(255,0,255)'>紫</button>"
"                        <button class='preset-btn' style='background:#17a2b8' onclick='setColor(0,255,255)'>青</button>"
"                        <button class='preset-btn' style='background:#fd7e14' onclick='setColor(255,128,0)'>橙</button>"
"                        <button class='preset-btn' style='background:#f8f9fa;color:#000;border:2px solid #dee2e6' onclick='setColor(255,255,255)'>白</button>"
"                    </div>"
"                </div>"
"            </div>"
"            <div class='preview-panel'>"
"                <div class='card preview-area'>"
"                    <h3>🎨 实时预览</h3>"
"                    <div class='color-preview' id='color-preview'></div>"
"                    <div class='color-info'>"
"                        <div class='info-item'>"
"                            <div class='info-label'>红色</div>"
"                            <div class='info-value' id='r-display'>255</div>"
"                        </div>"
"                        <div class='info-item'>"
"                            <div class='info-label'>绿色</div>"
"                            <div class='info-value' id='g-display'>255</div>"
"                        </div>"
"                        <div class='info-item'>"
"                            <div class='info-label'>蓝色</div>"
"                            <div class='info-value' id='b-display'>255</div>"
"                        </div>"
"                        <div class='info-item'>"
"                            <div class='info-label'>亮度</div>"
"                            <div class='info-value' id='brightness-display'>50%</div>"
"                        </div>"
"                    </div>"
"                </div>"
"                <div class='card'>"
"                    <h3>📶 网络状态</h3>"
"                    <div id='network-status'>正在获取状态...</div>"
"                    <div class='wifi-info'>"
"                        <p><strong>🌐 网络转发功能:</strong> 已启用</p>"
"                        <p><strong>📡 热点名称:</strong> ESP32-S3-LED</p>"
"                        <p><strong>🔐 热点密码:</strong> 12345678</p>"
"                        <p><strong>🌍 访问地址:</strong> 192.168.4.1</p>"
"                        <p><strong>💡 提示:</strong> 连接此热点后可正常上网</p>"
"                    </div>"
"                </div>"
"            </div>"
"        </div>"
"    </div>"
"    <script>"
"        let powerState = false;"
"        let currentColor = {r: 255, g: 255, b: 255};"
"        let currentBrightness = 50;"
"        let currentEffect = 'static';"
"        "
"        document.addEventListener('DOMContentLoaded', function() {"
"            setupEventListeners();"
"            updatePreview();"
"            getStatus();"
"            setInterval(getStatus, 5000);"
"        });"
"        "
"        function setupEventListeners() {"
"            document.getElementById('r-slider').oninput = updateColor;"
"            document.getElementById('g-slider').oninput = updateColor;"
"            document.getElementById('b-slider').oninput = updateColor;"
"            document.getElementById('brightness-slider').oninput = updateColor;"
"        }"
"        "
"        function updateColor() {"
"            currentColor.r = parseInt(document.getElementById('r-slider').value);"
"            currentColor.g = parseInt(document.getElementById('g-slider').value);"
"            currentColor.b = parseInt(document.getElementById('b-slider').value);"
"            currentBrightness = parseInt(document.getElementById('brightness-slider').value);"
"            updateDisplays();"
"            updatePreview();"
"            if(powerState) sendColorToDevice();"
"        }"
"        "
"        function updateDisplays() {"
"            document.getElementById('r-val').textContent = currentColor.r;"
"            document.getElementById('g-val').textContent = currentColor.g;"
"            document.getElementById('b-val').textContent = currentColor.b;"
"            document.getElementById('brightness-val').textContent = currentBrightness + '%';"
"            document.getElementById('r-display').textContent = currentColor.r;"
"            document.getElementById('g-display').textContent = currentColor.g;"
"            document.getElementById('b-display').textContent = currentColor.b;"
"            document.getElementById('brightness-display').textContent = currentBrightness + '%';"
"        }"
"        "
"        function updatePreview() {"
"            const preview = document.getElementById('color-preview');"
"            const factor = currentBrightness / 100;"
"            const r = Math.round(currentColor.r * factor);"
"            const g = Math.round(currentColor.g * factor);"
"            const b = Math.round(currentColor.b * factor);"
"            preview.style.background = `rgb(${r}, ${g}, ${b})`;"
"            if(currentBrightness > 30) {"
"                preview.style.boxShadow = `0 0 30px rgba(${r}, ${g}, ${b}, 0.6)`;"
"            } else {"
"                preview.style.boxShadow = '0 10px 30px rgba(0,0,0,0.2)';"
"            }"
"        }"
"        "
"        async function sendColorToDevice() {"
"            try {"
"                const response = await fetch('/api/led/color', {"
"                    method: 'POST',"
"                    headers: {'Content-Type': 'application/json'},"
"                    body: JSON.stringify({"
"                        r: currentColor.r,"
"                        g: currentColor.g,"
"                        b: currentColor.b,"
"                        brightness: currentBrightness"
"                    })"
"                });"
"                if(!response.ok) throw new Error('网络错误');"
"            } catch(e) {"
"                showNotification('颜色设置失败', 'error');"
"            }"
"        }"
"        "
"        async function togglePower() {"
"            powerState = !powerState;"
"            try {"
"                const response = await fetch('/api/led/power', {"
"                    method: 'POST',"
"                    headers: {'Content-Type': 'application/json'},"
"                    body: JSON.stringify({power: powerState})"
"                });"
"                if(response.ok) {"
"                    updatePowerButton();"
"                    if(powerState) sendColorToDevice();"
"                    showNotification(powerState ? 'LED已开启' : 'LED已关闭', 'success');"
"                } else {"
"                    powerState = !powerState;"
"                    throw new Error('操作失败');"
"                }"
"            } catch(e) {"
"                powerState = !powerState;"
"                showNotification('电源控制失败', 'error');"
"            }"
"        }"
"        "
"        function updatePowerButton() {"
"            const btn = document.getElementById('power-btn');"
"            if(powerState) {"
"                btn.textContent = '💡 关闭LED';"
"                btn.className = 'btn btn-power';"
"            } else {"
"                btn.textContent = '💡 开启LED';"
"                btn.className = 'btn btn-power off';"
"            }"
"        }"
"        "
"        async function setEffect(effect) {"
"            if(!powerState) {"
"                showNotification('请先开启LED', 'error');"
"                return;"
"            }"
"            try {"
"                const response = await fetch('/api/led/effect', {"
"                    method: 'POST',"
"                    headers: {'Content-Type': 'application/json'},"
"                    body: JSON.stringify({effect: effect})"
"                });"
"                if(response.ok) {"
"                    currentEffect = effect;"
"                    updateEffectButtons();"
"                    showNotification('特效已切换', 'success');"
"                } else {"
"                    throw new Error('操作失败');"
"                }"
"            } catch(e) {"
"                showNotification('特效设置失败', 'error');"
"            }"
"        }"
"        "
"        function updateEffectButtons() {"
"            document.querySelectorAll('.btn-effect').forEach(btn => {"
"                btn.classList.remove('active');"
"                if(btn.onclick.toString().includes(currentEffect)) {"
"                    btn.classList.add('active');"
"                }"
"            });"
"        }"
"        "
"        function setColor(r, g, b) {"
"            currentColor = {r, g, b};"
"            document.getElementById('r-slider').value = r;"
"            document.getElementById('g-slider').value = g;"
"            document.getElementById('b-slider').value = b;"
"            updateDisplays();"
"            updatePreview();"
"            if(powerState) sendColorToDevice();"
"        }"
"        "
"        async function getStatus() {"
"            try {"
"                const response = await fetch('/api/status');"
"                const data = await response.json();"
"                updateNetworkStatus(data);"
"            } catch(e) {"
"                document.getElementById('network-status').innerHTML = '<span style=\"color:red\">❌ 连接错误</span>';"
"            }"
"        }"
"        "
"        function updateNetworkStatus(data) {"
"            let statusHtml = '';"
"            if(data.wifi) {"
"                statusHtml += `<p><strong>📶 WiFi状态:</strong> ${data.wifi.connected ? '✅ 已连接' : '❌ 未连接'}</p>`;"
"                statusHtml += `<p><strong>🌐 IP地址:</strong> ${data.wifi.ip}</p>`;"
"                statusHtml += `<p><strong>🔥 热点模式:</strong> ${data.wifi.ap_mode ? '✅ 已开启' : '❌ 未开启'}</p>`;"
"            }"
"            if(data.led) {"
"                powerState = data.led.power;"
"                updatePowerButton();"
"            }"
"            if(data.uptime) {"
"                statusHtml += `<p><strong>⏱️ 运行时间:</strong> ${Math.floor(data.uptime/60)}分钟</p>`;"
"            }"
"            document.getElementById('network-status').innerHTML = statusHtml;"
"        }"
"        "
"        function showNotification(message, type) {"
"            const notification = document.createElement('div');"
"            notification.className = `notification ${type}`;"
"            notification.textContent = message;"
"            document.body.appendChild(notification);"
"            setTimeout(() => notification.classList.add('show'), 100);"
"            setTimeout(() => {"
"                notification.classList.remove('show');"
"                setTimeout(() => document.body.removeChild(notification), 300);"
"            }, 3000);"
"        }"
"    </script>"
"</body>"
"</html>";

// 获取HTML内容大小的函数
size_t get_index_html_size(void)
{
    return strlen(index_html_content);
}

// 获取HTML内容的函数
const char* get_index_html_content(void)
{
    return index_html_content;
}