/*
 * Web Files Implementation for ESP32-S3 LED Controller
 * 
 * 嵌入的Web文件内容
 */

#include "web_files.h"
#include <string.h>

// 简单的HTML页面内容
const char index_html_content[] = 
"<!DOCTYPE html>"
"<html lang=\"zh-CN\">"
"<head>"
"    <meta charset=\"UTF-8\">"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"    <title>ESP32-S3 LED控制器</title>"
"    <style>"
"        body {"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
"            margin: 0;"
"            padding: 20px;"
"            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
"            min-height: 100vh;"
"            color: #333;"
"        }"
"        .container {"
"            max-width: 800px;"
"            margin: 0 auto;"
"            background: white;"
"            border-radius: 15px;"
"            box-shadow: 0 10px 30px rgba(0,0,0,0.2);"
"            overflow: hidden;"
"        }"
"        .header {"
"            background: linear-gradient(45deg, #667eea, #764ba2);"
"            color: white;"
"            padding: 30px;"
"            text-align: center;"
"        }"
"        .header h1 {"
"            margin: 0;"
"            font-size: 2.5em;"
"            font-weight: 300;"
"        }"
"        .content {"
"            padding: 30px;"
"        }"
"        .control-section {"
"            margin-bottom: 30px;"
"            padding: 20px;"
"            border: 1px solid #e0e0e0;"
"            border-radius: 10px;"
"            background: #f9f9f9;"
"        }"
"        .control-section h3 {"
"            margin-top: 0;"
"            color: #667eea;"
"        }"
"        .color-picker {"
"            display: flex;"
"            gap: 15px;"
"            align-items: center;"
"            margin-bottom: 20px;"
"        }"
"        .color-input {"
"            width: 60px;"
"            height: 60px;"
"            border: none;"
"            border-radius: 10px;"
"            cursor: pointer;"
"        }"
"        .slider-container {"
"            flex: 1;"
"        }"
"        .slider {"
"            width: 100%;"
"            height: 8px;"
"            border-radius: 5px;"
"            background: #ddd;"
"            outline: none;"
"            margin: 10px 0;"
"        }"
"        .slider::-webkit-slider-thumb {"
"            appearance: none;"
"            width: 20px;"
"            height: 20px;"
"            border-radius: 50%;"
"            background: #667eea;"
"            cursor: pointer;"
"        }"
"        .button {"
"            background: linear-gradient(45deg, #667eea, #764ba2);"
"            color: white;"
"            border: none;"
"            padding: 12px 24px;"
"            border-radius: 25px;"
"            cursor: pointer;"
"            font-size: 16px;"
"            margin: 5px;"
"            transition: transform 0.2s;"
"        }"
"        .button:hover {"
"            transform: translateY(-2px);"
"        }"
"        .button:active {"
"            transform: translateY(0);"
"        }"
"        .status {"
"            background: #e8f5e8;"
"            border: 1px solid #4caf50;"
"            border-radius: 10px;"
"            padding: 15px;"
"            margin-bottom: 20px;"
"        }"
"        .wifi-section {"
"            background: #fff3cd;"
"            border: 1px solid #ffc107;"
"            border-radius: 10px;"
"            padding: 15px;"
"            margin-bottom: 20px;"
"        }"
"        .wifi-form {"
"            display: flex;"
"            gap: 10px;"
"            flex-wrap: wrap;"
"        }"
"        .wifi-input {"
"            flex: 1;"
"            min-width: 200px;"
"            padding: 10px;"
"            border: 1px solid #ddd;"
"            border-radius: 5px;"
"            font-size: 14px;"
"        }"
"        .preset-colors {"
"            display: grid;"
"            grid-template-columns: repeat(auto-fit, minmax(60px, 1fr));"
"            gap: 10px;"
"            margin-top: 15px;"
"        }"
"        .preset-color {"
"            width: 60px;"
"            height: 60px;"
"            border-radius: 10px;"
"            border: 3px solid transparent;"
"            cursor: pointer;"
"            transition: border-color 0.2s;"
"        }"
"        .preset-color:hover {"
"            border-color: #667eea;"
"        }"
"        @media (max-width: 600px) {"
"            .header h1 {"
"                font-size: 2em;"
"            }"
"            .content {"
"                padding: 20px;"
"            }"
"            .wifi-form {"
"                flex-direction: column;"
"            }"
"        }"
"    </style>"
"</head>"
"<body>"
"    <div class=\"container\">"
"        <div class=\"header\">"
"            <h1>🎨 ESP32-S3 LED控制器</h1>"
"            <p>智能RGB LED控制面板</p>"
"        </div>"
"        <div class=\"content\">"
"            <div class=\"status\" id=\"status\">"
"                <strong>系统状态:</strong> 正在连接..."
"            </div>"
"            <div class=\"wifi-section\">"
"                <h3>📶 WiFi连接</h3>"
"                <div class=\"wifi-form\">"
"                    <input type=\"text\" id=\"ssid\" class=\"wifi-input\" placeholder=\"WiFi名称 (SSID)\">"
"                    <input type=\"password\" id=\"password\" class=\"wifi-input\" placeholder=\"WiFi密码\">"
"                    <button class=\"button\" onclick=\"connectWiFi()\">连接</button>"
"                </div>"
"                <p><small>热点名称: ESP32-S3-LED, 密码: 12345678</small></p>"
"            </div>"
"            <div class=\"control-section\">"
"                <h3>🎛️ LED控制</h3>"
"                <div class=\"color-picker\">"
"                    <input type=\"color\" id=\"colorPicker\" class=\"color-input\" value=\"#ffffff\">"
"                    <div class=\"slider-container\">"
"                        <label>亮度: <span id=\"brightnessValue\">50</span>%</label>"
"                        <input type=\"range\" id=\"brightness\" class=\"slider\" min=\"0\" max=\"100\" value=\"50\">"
"                    </div>"
"                </div>"
"                <div>"
"                    <button class=\"button\" onclick=\"togglePower()\" id=\"powerBtn\">开启</button>"
"                    <button class=\"button\" onclick=\"setEffect('rainbow')\">彩虹</button>"
"                    <button class=\"button\" onclick=\"setEffect('breath')\">呼吸</button>"
"                    <button class=\"button\" onclick=\"setEffect('blink')\">闪烁</button>"
"                    <button class=\"button\" onclick=\"setEffect('none')\">关闭特效</button>"
"                </div>"
"                <div class=\"preset-colors\">"
"                    <div class=\"preset-color\" style=\"background: #ff0000;\" onclick=\"setPresetColor('#ff0000')\"></div>"
"                    <div class=\"preset-color\" style=\"background: #00ff00;\" onclick=\"setPresetColor('#00ff00')\"></div>"
"                    <div class=\"preset-color\" style=\"background: #0000ff;\" onclick=\"setPresetColor('#0000ff')\"></div>"
"                    <div class=\"preset-color\" style=\"background: #ffff00;\" onclick=\"setPresetColor('#ffff00')\"></div>"
"                    <div class=\"preset-color\" style=\"background: #ff00ff;\" onclick=\"setPresetColor('#ff00ff')\"></div>"
"                    <div class=\"preset-color\" style=\"background: #00ffff;\" onclick=\"setPresetColor('#00ffff')\"></div>"
"                    <div class=\"preset-color\" style=\"background: #ffa500;\" onclick=\"setPresetColor('#ffa500')\"></div>"
"                    <div class=\"preset-color\" style=\"background: #800080;\" onclick=\"setPresetColor('#800080')\"></div>"
"                </div>"
"            </div>"
"        </div>"
"    </div>"
"    <script>"
"        let currentStatus = {};"
"        function updateStatus() {"
"            fetch('/api/status')"
"                .then(response => response.json())"
"                .then(data => {"
"                    currentStatus = data;"
"                    const statusDiv = document.getElementById('status');"
"                    const powerBtn = document.getElementById('powerBtn');"
"                    let statusText = '<strong>系统状态:</strong> ';"
"                    if (data.wifi.connected) {"
"                        statusText += '已连接到 ' + data.wifi.ip;"
"                    } else if (data.wifi.ap_mode) {"
"                        statusText += '热点模式 (192.168.4.1)';"
"                    } else {"
"                        statusText += '未连接';"
"                    }"
"                    statusText += ' | 运行时间: ' + Math.floor(data.uptime / 60) + '分钟 | 内存: ' + Math.floor(data.free_heap / 1024) + 'KB';"
"                    statusDiv.innerHTML = statusText;"
"                    powerBtn.textContent = data.led.power ? '关闭' : '开启';"
"                    const colorPicker = document.getElementById('colorPicker');"
"                    const brightnessSlider = document.getElementById('brightness');"
"                    const brightnessValue = document.getElementById('brightnessValue');"
"                    const r = data.led.r.toString(16).padStart(2, '0');"
"                    const g = data.led.g.toString(16).padStart(2, '0');"
"                    const b = data.led.b.toString(16).padStart(2, '0');"
"                    colorPicker.value = '#' + r + g + b;"
"                    brightnessSlider.value = data.led.brightness;"
"                    brightnessValue.textContent = data.led.brightness;"
"                })"
"                .catch(error => {"
"                    console.error('Error fetching status:', error);"
"                });"
"        }"
"        function setColor(color, brightness) {"
"            const r = parseInt(color.substr(1, 2), 16);"
"            const g = parseInt(color.substr(3, 2), 16);"
"            const b = parseInt(color.substr(5, 2), 16);"
"            fetch('/api/led/color', {"
"                method: 'POST',"
"                headers: {"
"                    'Content-Type': 'application/json',"
"                },"
"                body: JSON.stringify({"
"                    r: r,"
"                    g: g,"
"                    b: b,"
"                    brightness: brightness"
"                })"
"            });"
"        }"
"        function togglePower() {"
"            fetch('/api/led/power', {"
"                method: 'POST',"
"                headers: {"
"                    'Content-Type': 'application/json',"
"                },"
"                body: JSON.stringify({"
"                    power: !currentStatus.led.power"
"                })"
"            }).then(() => updateStatus());"
"        }"
"        function setEffect(effect) {"
"            fetch('/api/led/effect', {"
"                method: 'POST',"
"                headers: {"
"                    'Content-Type': 'application/json',"
"                },"
"                body: JSON.stringify({"
"                    effect: effect"
"                })"
"            });"
"        }"
"        function connectWiFi() {"
"            const ssid = document.getElementById('ssid').value;"
"            const password = document.getElementById('password').value;"
"            if (!ssid || !password) {"
"                alert('请输入WiFi名称和密码');"
"                return;"
"            }"
"            fetch('/api/wifi/connect', {"
"                method: 'POST',"
"                headers: {"
"                    'Content-Type': 'application/json',"
"                },"
"                body: JSON.stringify({"
"                    ssid: ssid,"
"                    password: password"
"                })"
"            }).then(response => {"
"                if (response.ok) {"
"                    alert('正在连接WiFi...');"
"                } else {"
"                    alert('连接失败');"
"                }"
"            });"
"        }"
"        function setPresetColor(color) {"
"            const brightness = document.getElementById('brightness').value;"
"            setColor(color, parseInt(brightness));"
"        }"
"        document.getElementById('colorPicker').addEventListener('change', function() {"
"            const brightness = document.getElementById('brightness').value;"
"            setColor(this.value, parseInt(brightness));"
"        });"
"        document.getElementById('brightness').addEventListener('input', function() {"
"            document.getElementById('brightnessValue').textContent = this.value;"
"            const colorPicker = document.getElementById('colorPicker');"
"            setColor(colorPicker.value, parseInt(this.value));"
"        });"
"        setInterval(updateStatus, 2000);"
"        updateStatus();"
"    </script>"
"</body>"
"</html>";

// 导出Web文件内容
extern const char index_html_start[] asm("_binary_index_html_start");
extern const char index_html_end[] asm("_binary_index_html_end");

// 临时实现：返回HTML内容
const char* get_index_html_content(void)
{
    return index_html_content;
}

size_t get_index_html_size(void)
{
    return strlen(index_html_content);
}
